# docker-aws-cicd-example/docker-compose.yml

version: '3.8' 

services:
  # 백엔드 서비스 설정
  backend:
    build: ./backend # 
    ports:
      - "3001:3001" 
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    depends_on: # 의존성 설정
      - db 

  # 프론트엔드 서비스 설정
  frontend:
    build: ./frontend 
    ports:
      - "8080:80" 
    depends_on: 
      - backend 

  # 데이터베이스 서비스 설정 (PostgreSQL)
  db:
    image: postgres:15-alpine 
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: exampleuser 
      POSTGRES_PASSWORD: examplepass 
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local 