# .github/workflows/main.yml

name: CI/CD Pipeline - Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    name: Build and Push Docker Images to ECR
    runs-on: ubuntu-latest
    outputs:
      backend_image_latest: ${{ steps.image_details.outputs.BACKEND_IMAGE_LATEST_OUTPUT }}
      backend_image_commit: ${{ steps.image_details.outputs.BACKEND_IMAGE_COMMIT_OUTPUT }}
      frontend_image_latest: ${{ steps.image_details.outputs.FRONTEND_IMAGE_LATEST_OUTPUT }}
      frontend_image_commit: ${{ steps.image_details.outputs.FRONTEND_IMAGE_COMMIT_OUTPUT }}
      simple_test_passed: ${{ steps.image_details.outputs.MY_SIMPLE_TEST_OUTPUT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image details and export for other jobs
        id: image_details
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_BACKEND: ${{ secrets.ECR_REPOSITORY_BACKEND }}
          ECR_REPOSITORY_FRONTEND: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
          IMAGE_TAG_LATEST: latest
          IMAGE_TAG_COMMIT_SHA: ${{ github.sha }}
        run: |
          COMMIT_SHA_SHORT=$(echo ${IMAGE_TAG_COMMIT_SHA} | cut -c1-7)
          
          echo "BACKEND_IMAGE_LATEST_ENV=${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${IMAGE_TAG_LATEST}" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_COMMIT_ENV=${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${COMMIT_SHA_SHORT}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_LATEST_ENV=${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${IMAGE_TAG_LATEST}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_COMMIT_ENV=${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${COMMIT_SHA_SHORT}" >> $GITHUB_ENV

          BACKEND_LATEST_URI_VAL="${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${IMAGE_TAG_LATEST}"
          BACKEND_COMMIT_URI_VAL="${ECR_REGISTRY}/${ECR_REPOSITORY_BACKEND}:${COMMIT_SHA_SHORT}"
          FRONTEND_LATEST_URI_VAL="${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${IMAGE_TAG_LATEST}"
          FRONTEND_COMMIT_URI_VAL="${ECR_REGISTRY}/${ECR_REPOSITORY_FRONTEND}:${COMMIT_SHA_SHORT}"

          echo "Debug - ECR_REGISTRY is: ${ECR_REGISTRY}"
          echo "Debug - ECR_REPOSITORY_BACKEND is: ${ECR_REPOSITORY_BACKEND}"
          echo "Debug - ECR_REPOSITORY_FRONTEND is: ${ECR_REPOSITORY_FRONTEND}"
          echo "Debug - COMMIT_SHA_SHORT is: ${COMMIT_SHA_SHORT}"

          echo "Debug - BACKEND_IMAGE_LATEST_OUTPUT will be: $BACKEND_LATEST_URI_VAL"
          echo "Debug - BACKEND_IMAGE_COMMIT_OUTPUT will be: $BACKEND_COMMIT_URI_VAL"
          echo "Debug - FRONTEND_IMAGE_LATEST_OUTPUT will be: $FRONTEND_LATEST_URI_VAL"
          echo "Debug - FRONTEND_IMAGE_COMMIT_OUTPUT will be: $FRONTEND_COMMIT_URI_VAL"
          echo "Debug - Simple test output will be: HelloFromJob1"
          
          # 다른 작업으로 전달될 출력값 설정 (값 부분을 따옴표로 감싸봄)
          echo "BACKEND_IMAGE_LATEST_OUTPUT=\"${BACKEND_LATEST_URI_VAL}\"" >> $GITHUB_OUTPUT
          echo "BACKEND_IMAGE_COMMIT_OUTPUT=\"${BACKEND_COMMIT_URI_VAL}\"" >> $GITHUB_OUTPUT
          echo "FRONTEND_IMAGE_LATEST_OUTPUT=\"${FRONTEND_LATEST_URI_VAL}\"" >> $GITHUB_OUTPUT
          echo "FRONTEND_IMAGE_COMMIT_OUTPUT=\"${FRONTEND_COMMIT_URI_VAL}\"" >> $GITHUB_OUTPUT
          echo "MY_SIMPLE_TEST_OUTPUT=\"HelloFromJob1\"" >> $GITHUB_OUTPUT
          
          echo "--- Content of GITHUB_OUTPUT file ---"
          cat $GITHUB_OUTPUT
          echo "-------------------------------------"

      - name: Build, tag, and push backend image to Amazon ECR
        run: |
          docker build -t ${{ env.BACKEND_IMAGE_LATEST_ENV }} -t ${{ env.BACKEND_IMAGE_COMMIT_ENV }} ./backend
          docker push ${{ env.BACKEND_IMAGE_LATEST_ENV }}
          docker push ${{ env.BACKEND_IMAGE_COMMIT_ENV }}

      - name: Build, tag, and push frontend image to Amazon ECR
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE_LATEST_ENV }} -t ${{ env.FRONTEND_IMAGE_COMMIT_ENV }} ./frontend
          docker push ${{ env.FRONTEND_IMAGE_LATEST_ENV }}
          docker push ${{ env.FRONTEND_IMAGE_COMMIT_ENV }}

  deploy-to-ec2:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest
    needs: build-and-push-images
    env: 
      PASSED_BACKEND_IMAGE_URI: ${{ needs.build-and-push-images.outputs.backend_image_commit }}
      PASSED_FRONTEND_IMAGE_URI: ${{ needs.build-and-push-images.outputs.frontend_image_commit }}
      PASSED_SIMPLE_TEST: ${{ needs.build-and-push-images.outputs.simple_test_passed }}
      POSTGRES_USER: exampleuser 
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
      APP_DIR: /home/${{ secrets.EC2_USER }}/app

    steps:
      - name: Print Entire Needs Context for Debugging
        run: echo "${{ toJSON(needs) }}"

      - name: Print Received Values for Debugging
        run: |
          echo "Received for deploy - Backend Image URI: ${{ env.PASSED_BACKEND_IMAGE_URI }}"
          echo "Received for deploy - Frontend Image URI: ${{ env.PASSED_FRONTEND_IMAGE_URI }}"
          echo "Received for deploy - Simple Test Value: ${{ env.PASSED_SIMPLE_TEST }}"

      - name: Deploy to EC2 server using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "--- Environment variables available in SSH script ---"
            echo "PASSED_BACKEND_IMAGE_URI is: $PASSED_BACKEND_IMAGE_URI" # 셸 변수로 참조
            echo "PASSED_FRONTEND_IMAGE_URI is: $PASSED_FRONTEND_IMAGE_URI" # 셸 변수로 참조
            echo "PASSED_SIMPLE_TEST is: $PASSED_SIMPLE_TEST"
            echo "APP_DIR is: $APP_DIR"
            echo "POSTGRES_USER is: $POSTGRES_USER"
            echo "-----------------------------------------------------"

            mkdir -p ${{ env.APP_DIR }} # GitHub Actions env 변수 사용
            cd ${{ env.APP_DIR }}

            echo 'version: "3.8" # 또는 이 줄 삭제
            services:
              backend:
                image: ${{ env.PASSED_BACKEND_IMAGE_URI }} # GitHub Actions 표현식 사용
                ports:
                  - "3001:3001"
                environment:
                  NODE_ENV: production
                  DB_USER: ${{ env.POSTGRES_USER }}
                  DB_HOST: db 
                  DB_NAME: ${{ env.POSTGRES_DB }}
                  DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
                  DB_PORT: 5432
                depends_on:
                  - db
              frontend:
                image: ${{ env.PASSED_FRONTEND_IMAGE_URI }} # GitHub Actions 표현식 사용
                ports:
                  - "80:80" 
                depends_on:
                  - backend
              db:
                image: postgres:15-alpine
                environment:
                  POSTGRES_USER: ${{ env.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
                  POSTGRES_DB: ${{ env.POSTGRES_DB }}
                volumes:
                  - postgres_data:/var/lib/postgresql/data
            volumes:
              postgres_data:
                driver: local
            ' > docker-compose.yml

            echo "--- Generated docker-compose.yml content on EC2 ---"
            cat docker-compose.yml
            echo "-----------------------------------------------------"

            echo "Pulling latest images from ECR..."
            docker-compose pull

            echo "Starting application with new images..."
            docker-compose up -d --remove-orphans

            echo "Cleaning up old Docker images..."
            docker image prune -af