# .github/workflows/main.yml

name: CI/CD Pipeline - Build, Push to ECR, and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-images:
    name: Build and Push Docker Images to ECR
    runs-on: ubuntu-latest
    outputs:
      # 매우 단순한 이름으로 변경
      registry: ${{ steps.image_details.outputs.registry_out }}
      b_repo: ${{ steps.image_details.outputs.b_repo_out }}
      f_repo: ${{ steps.image_details.outputs.f_repo_out }}
      tag_commit: ${{ steps.image_details.outputs.tag_commit_out }}
      test_val: ${{ steps.image_details.outputs.test_val_out }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image details and export for other jobs
        id: image_details
        env:
          ECR_REGISTRY_ENV: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_BACKEND_ENV: ${{ secrets.ECR_REPOSITORY_BACKEND }}
          ECR_REPOSITORY_FRONTEND_ENV: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
          IMAGE_TAG_LATEST_ENV: latest # 이 값은 이제 다음 job으로 직접 전달하지 않음
          IMAGE_TAG_COMMIT_SHA_ENV: ${{ github.sha }}
        run: |
          COMMIT_SHA_SHORT=$(echo ${IMAGE_TAG_COMMIT_SHA_ENV} | cut -c1-7)
          
          # 현재 작업용 환경 변수 설정 (빌드 시 사용)
          echo "BACKEND_IMAGE_LATEST_FOR_BUILD=${ECR_REGISTRY_ENV}/${ECR_REPOSITORY_BACKEND_ENV}:${IMAGE_TAG_LATEST_ENV}" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_COMMIT_FOR_BUILD=${ECR_REGISTRY_ENV}/${ECR_REPOSITORY_BACKEND_ENV}:${COMMIT_SHA_SHORT}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_LATEST_FOR_BUILD=${ECR_REGISTRY_ENV}/${ECR_REPOSITORY_FRONTEND_ENV}:${IMAGE_TAG_LATEST_ENV}" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_COMMIT_FOR_BUILD=${ECR_REGISTRY_ENV}/${ECR_REPOSITORY_FRONTEND_ENV}:${COMMIT_SHA_SHORT}" >> $GITHUB_ENV
          
          # 디버깅 로그 (이전과 동일하게 유지)
          echo "Debug - ECR_REGISTRY_ENV for output: ${ECR_REGISTRY_ENV}"
          echo "Debug - BACKEND_REPO_NAME_ENV for output: ${ECR_REPOSITORY_BACKEND_ENV}"
          echo "Debug - FRONTEND_REPO_NAME_ENV for output: ${ECR_REPOSITORY_FRONTEND_ENV}"
          echo "Debug - COMMIT_SHA_SHORT for output: ${COMMIT_SHA_SHORT}"
          
          # 다른 작업으로 전달될 출력값 설정 (매우 단순한 키 이름 사용)
          echo "registry_out=${ECR_REGISTRY_ENV}" >> $GITHUB_OUTPUT
          echo "b_repo_out=${ECR_REPOSITORY_BACKEND_ENV}" >> $GITHUB_OUTPUT
          echo "f_repo_out=${ECR_REPOSITORY_FRONTEND_ENV}" >> $GITHUB_OUTPUT
          echo "tag_commit_out=${COMMIT_SHA_SHORT}" >> $GITHUB_OUTPUT
          echo "test_val_out=TestSuccessful" >> $GITHUB_OUTPUT # 단순 테스트 값 변경
          
          echo "--- Content of GITHUB_OUTPUT file ---"
          cat $GITHUB_OUTPUT
          echo "-------------------------------------"

      - name: Build, tag, and push backend image to Amazon ECR
        run: |
          docker build -t ${{ env.BACKEND_IMAGE_LATEST_FOR_BUILD }} -t ${{ env.BACKEND_IMAGE_COMMIT_FOR_BUILD }} ./backend
          docker push ${{ env.BACKEND_IMAGE_LATEST_FOR_BUILD }}
          docker push ${{ env.BACKEND_IMAGE_COMMIT_FOR_BUILD }}

      - name: Build, tag, and push frontend image to Amazon ECR
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE_LATEST_FOR_BUILD }} -t ${{ env.FRONTEND_IMAGE_COMMIT_FOR_BUILD }} ./frontend
          docker push ${{ env.FRONTEND_IMAGE_LATEST_FOR_BUILD }}
          docker push ${{ env.FRONTEND_IMAGE_COMMIT_FOR_BUILD }}

  deploy-to-ec2:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest
    needs: build-and-push-images
    env: 
      # 이전 작업의 단순화된 출력값을 받음
      TARGET_ECR_REGISTRY: ${{ needs.build-and-push-images.outputs.registry }}
      TARGET_BACKEND_REPO: ${{ needs.build-and-push-images.outputs.b_repo }}
      TARGET_FRONTEND_REPO: ${{ needs.build-and-push-images.outputs.f_repo }}
      TARGET_TAG_COMMIT: ${{ needs.build-and-push-images.outputs.tag_commit }}
      TARGET_SIMPLE_TEST: ${{ needs.build-and-push-images.outputs.test_val }}
      
      POSTGRES_USER: exampleuser 
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
      APP_DIR: /home/${{ secrets.EC2_USER }}/app

    steps:
      - name: Construct Full Image URIs and Print for Debugging
        id: construct_uris
        run: |
          echo "Debug - Received TARGET_ECR_REGISTRY: ${{ env.TARGET_ECR_REGISTRY }}"
          echo "Debug - Received TARGET_BACKEND_REPO: ${{ env.TARGET_BACKEND_REPO }}"
          echo "Debug - Received TARGET_FRONTEND_REPO: ${{ env.TARGET_FRONTEND_REPO }}"
          echo "Debug - Received TARGET_TAG_COMMIT: ${{ env.TARGET_TAG_COMMIT }}"
          echo "Debug - Received TARGET_SIMPLE_TEST: ${{ env.TARGET_SIMPLE_TEST }}"

          FINAL_BACKEND_IMAGE_URI="${{ env.TARGET_ECR_REGISTRY }}/${{ env.TARGET_BACKEND_REPO }}:${{ env.TARGET_TAG_COMMIT }}"
          FINAL_FRONTEND_IMAGE_URI="${{ env.TARGET_ECR_REGISTRY }}/${{ env.TARGET_FRONTEND_REPO }}:${{ env.TARGET_TAG_COMMIT }}"
          
          echo "Constructed - Backend Image URI: ${FINAL_BACKEND_IMAGE_URI}"
          echo "Constructed - Frontend Image URI: ${FINAL_FRONTEND_IMAGE_URI}"
          
          echo "FINAL_BACKEND_URI_ENV=${FINAL_BACKEND_IMAGE_URI}" >> $GITHUB_ENV
          echo "FINAL_FRONTEND_URI_ENV=${FINAL_FRONTEND_IMAGE_URI}" >> $GITHUB_ENV

      - name: Deploy to EC2 server using SSH
        uses: appleboy/ssh-action@v1.0.3 # 또는 사용하시던 버전
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "--- Environment variables for docker-compose.yml generation ---"
            echo "Backend Image for compose: ${{ env.FINAL_BACKEND_URI_ENV }}"
            echo "Frontend Image for compose: ${{ env.FINAL_FRONTEND_URI_ENV }}"
            echo "-------------------------------------------------------------"

            mkdir -p ${{ env.APP_DIR }}
            cd ${{ env.APP_DIR }}

            # docker-compose.yml 생성 (이전과 거의 동일, 이미지 부분만 확인)
            echo 'version: "3.8"
            services:
              backend:
                image: ${{ env.FINAL_BACKEND_URI_ENV }}
                ports: ["3001:3001"]
                environment:
                  NODE_ENV: production
                  DB_USER: ${{ env.POSTGRES_USER }}
                  DB_HOST: db 
                  DB_NAME: ${{ env.POSTGRES_DB }}
                  DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
                  DB_PORT: 5432
                depends_on: [- db]
              frontend:
                image: ${{ env.FINAL_FRONTEND_URI_ENV }}
                ports: ["80:80"]
                depends_on: [- backend]
              db:
                image: postgres:15-alpine
                environment:
                  POSTGRES_USER: ${{ env.POSTGRES_USER }}
                  POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
                  POSTGRES_DB: ${{ env.POSTGRES_DB }}
                volumes: [- postgres_data:/var/lib/postgresql/data]
            volumes:
              postgres_data:
                driver: local
            ' > docker-compose.yml

            echo "--- Generated docker-compose.yml content on EC2 ---"
            cat docker-compose.yml
            echo "-----------------------------------------------------"

            docker-compose pull
            docker-compose up -d --remove-orphans
            docker image prune -af